In [1]:
import numpy as np
import pandas as pd
import datetime

import matplotlib.pyplot as plt

plt.style.use('fivethirtyeight')

In [2]:
pd.read_parquet("../data/01_raw/btc_raw_history_1d.parquet")

,date,high,low,open,close,volume,adjclose,formatted_date
0,1609459200,29600.626953,28803.585938,28994.009766,29374.152344,40730301359,29374.152344,2021-01-01
1,1609545600,33155.117188,29091.181641,29376.455078,32127.267578,67865420765,32127.267578,2021-01-02
2,1609632000,34608.558594,32052.316406,32129.408203,32782.023438,78665235202,32782.023438,2021-01-03
3,1609718400,33440.218750,28722.755859,32810.949219,31971.914062,81163475344,31971.914062,2021-01-04
4,1609804800,34437.589844,30221.187500,31977.041016,33992.429688,67547324782,33992.429688,2021-01-05
...,...,...,...,...,...,...,...,...
1115,1705795200,41855.367188,41497.007812,41671.488281,41545.785156,9344043642,41545.785156,2024-01-21
1116,1705881600,41651.207031,39450.117188,41553.652344,39507.367188,31338708143,39507.367188,2024-01-22
1117,1705968000,40127.351562,38521.894531,39518.714844,39845.550781,29244553045,39845.550781,2024-01-23
1118,1706054400,40483.785156,39508.796875,39877.593750,40077.074219,22359526178,40077.074219,2024-01-24
1119,1706186820,40254.480469,39803.648438,40075.550781,39855.472656,19443650560,39855.472656,2024-01-25